[mbox]
# Path to your mbox file
path= "all.mbox"
# Where to "dump" the emails, defaults to \Archive
dest = "\\Archive"
# List of your emails will direct emails from you to \Sent
emails = ["bye@protonmail.com"]

[imap]
tz_offset = 28800 # seconds
domain = "imap.fastmail.com"
port = 993
username = ""
password = ""
