[mbox]
# Path to your mbox file
path= "all.mbox"
# Where to "dump" the emails, defaults to \Archive
dest = "\\Archive"
# List of your emails will direct emails from you to \Sent
emails = ["company@example.com"]

[imap]
tz_offset = 28800 # seconds
domain = ""
port = 993
username = ""
password = ""
